baseURL = ""
languageCode = "en-us"
rssLimit = 25
title = "Donny Winston"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 4
summaryLength = 10

[taxonomies]
  tag = "tags"

[author]
	name = "Donny"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "Made as simple as possible, but not simpler."

    # Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
    enableKofi = false
    kofi = ""

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
	email = "mailto:mail@donnywinston.com"
	linkedin = "https://www.linkedin.com/in/donnywinston/"

	# Programming
    github = "https://github.com/dwinston/"
	# stackoverflow = "#"

    # Academic
    # googlescholar = "#"
    # orcid = "#" 

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "consulting"
	name = "Consulting"
	url = "/consulting/"
	weight = 2

#[[menu.main]]
#	identifier = "tags"
#	name = "Tags"
#	url = "/tags/"
#	weight = 3

[[menu.main]]
	name = "Archives"
	identifier = "archives"
	url = "/archives/"
	weight = 4

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true