
name: Email New Posts

on:
  push:
    branches: [ master ]
    paths:
      - 'content/posts/*.md'

jobs:
  sendmail:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Check and send
        run: |
          python buttondown_post.py
